### ISSUE TITLE
Button "Teleport" in the GUI menu should not work when the user doesn't have the `teleport` privilege

### ISSUE THREAD

**Issue by rodrigo-morales-1** [carloschon/simple_waypoints#2] opened 2024-11-07 22:29 UTC
# What happens

A user without the `teleport` privilege can teleport to a waypoint by pressing the button "Teleport" in the GUI menu.

# What should happen

A user without the `teleport` privilege should not be able to use the button "Teleport" in the GUI menu.

**Comment by carloschon** [comment] 2024-11-10 13:05
Closing this since the Issue is fixed by [this](https://github.com/carloschon/simple_waypoints/commit/9d4bcf56e3567df8eefca4b7d1cc0569b1face49) commit.

**Closed as completed by carloschon** 2024-11-10 13:05 UTC
